[package]
name = "exifmv"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"
description = "Moves images into a folder hierarchy based on EXIF tags"

[[bin]]
name = "exifmv"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
error-chain = "0.12.4"
kamadak-exif = "0.5.4"
shellexpand = "2.1.0"
walkdir = "2.3.2"

[dependencies.clap]
version = "3.0.5"
default-features = true
features = ["wrap_help", "color", "suggestions"]

[profile.release]
opt-level = 'z' # Optimize for size.
lto = true
panic = 'abort'
codegen-units = 1
