[package]
name = "exifmv"
version = "0.1.3"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2021"
license = "Apache-2.0 OR BSD-3-Clause OR MIT OR Zlib"
description = "Moves images into a folder hierarchy based on EXIF tags"
keywords = ["graphics", "images", "organzing", "sorting", "exif"]
categories = ["command-line-utilities", "graphics", "multimedia::images", "filesystem"]
exclude = [".github/**/*", "test/**/*"]
readme = "README.md"
documentation = "https://docs.rs/exifmv/"
repository = "https://github.com/virtualritz/exifmv/"

[badges]
maintenance = { status = "passively-maintained" }

[[bin]]
name = "exifmv"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
error-chain = "0.12.4"
kamadak-exif = "0.5.4"
shellexpand = "2.1.0"
walkdir = "2.3.2"

[dependencies.clap]
version = "4.1.1"
default-features = true
features = ["wrap_help", "color", "suggestions"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
