[package]
name = "exifmv"
version = "0.2.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2021"
license = "Apache-2.0 OR BSD-3-Clause OR MIT OR Zlib"
description = "Moves images into a folder hierarchy based on EXIF tags"
keywords = ["graphics", "images", "organzing", "sorting", "exif"]
categories = ["command-line-utilities", "graphics", "multimedia::images", "filesystem"]
exclude = [".github/**/*", "test/**/*"]
readme = "README.md"
documentation = "https://docs.rs/exifmv/"
repository = "https://github.com/virtualritz/exifmv/"

[badges]
maintenance = { status = "passively-maintained" }

[[bin]]
name = "exifmv"
path = "src/main.rs"

[dependencies]
chrono = "0.4.24"
clap = "3.2.23"
error-chain = "0.12.4"
kamadak-exif = "0.5.5"
trash = "3.0.1"
walkdir = "2.3.3"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
