[package]
name = "exifmv"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@protonmail.com>"]
edition = "2018"
description = "Moves images into a folder hierarchy based on EXIF tags"

[[bin]]
name = "exifmv"
path = "src/main.rs" 

[dependencies]
chrono = "0.4.11"
colored = "2.0.0"
error-chain = "0.12.2"
kamadak-exif = "0.5.1"
shellexpand = "2.0.0"
walkdir = "2.3.1"

[dependencies.clap]
version = "2.33.0"
default-features = true
features = [ "wrap_help" ]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
codegen-units = 1
